var manifest = {
    spriteData: {
        "agent": "sprites/agent.json",
        "arrow": "sprites/arrow.json",
        "axe": "sprites/axe.json",
        "bat": "sprites/bat.json",
        "beachnpc": "sprites/beachnpc.json",
        "bluesword": "sprites/bluesword.json",
        "boss": "sprites/boss.json",
        "chest": "sprites/chest.json",
        "clotharmor": "sprites/clotharmor.json",
        "coder": "sprites/coder.json",
        "crab": "sprites/crab.json",
        "death": "sprites/death.json",
        "deathknight": "sprites/deathknight.json",
        "desertnpc": "sprites/desertnpc.json",
        "eye": "sprites/eye.json",
        "firefox": "sprites/firefox.json",
        "forestnpc": "sprites/forestnpc.json",
        "goblin": "sprites/goblin.json",
        "goldenarmor": "sprites/goldenarmor.json",
        "goldensword": "sprites/goldensword.json",
        "guard": "sprites/guard.json",
        "hand": "sprites/hand.json",
        "impact": "sprites/impact.json",
        "item-axe": "sprites/item-axe.json",
        "item-bluesword": "sprites/item-bluesword.json",
        "item-burger": "sprites/item-burger.json",
        "item-cake": "sprites/item-cake.json",
        "item-clotharmor": "sprites/item-clotharmor.json",
        "item-firepotion": "sprites/item-firepotion.json",
        "item-flask": "sprites/item-flask.json",
        "item-goldenarmor": "sprites/item-goldenarmor.json",
        "item-goldensword": "sprites/item-goldensword.json",
        "item-leatherarmor": "sprites/item-leatherarmor.json",
        "item-mailarmor": "sprites/item-mailarmor.json",
        "item-morningstar": "sprites/item-morningstar.json",
        "item-platearmor": "sprites/item-platearmor.json",
        "item-redarmor": "sprites/item-redarmor.json",
        "item-redsword": "sprites/item-redsword.json",
        "item-sword1": "sprites/item-sword1.json",
        "item-sword2": "sprites/item-sword2.json",
        "king": "sprites/king.json",
        "lavanpc": "sprites/lavanpc.json",
        "leatherarmor": "sprites/leatherarmor.json",
        "loot": "sprites/loot.json",
        "mailarmor": "sprites/mailarmor.json",
        "morningstar": "sprites/morningstar.json",
        "nyan": "sprites/nyan.json",
        "octocat": "sprites/octocat.json",
        "ogre": "sprites/ogre.json",
        "platearmor": "sprites/platearmor.json",
        "priest": "sprites/priest.json",
        "rat": "sprites/rat.json",
        "redarmor": "sprites/redarmor.json",
        "redsword": "sprites/redsword.json",
        "rick": "sprites/rick.json",
        "scientist": "sprites/scientist.json",
        "shadow16": "sprites/shadow16.json",
        "skeleton": "sprites/skeleton.json",
        "skeleton2": "sprites/skeleton2.json",
        "snake": "sprites/snake.json",
        "sorcerer": "sprites/sorcerer.json",
        "sparks": "sprites/sparks.json",
        "spectre": "sprites/spectre.json",
        "sword": "sprites/sword.json",
        "sword1": "sprites/sword1.json",
        "sword2": "sprites/sword2.json",
        "talk": "sprites/talk.json",
        "target": "sprites/target.json",
        "villagegirl": "sprites/villagegirl.json",
        "villager": "sprites/villager.json",
        "wizard": "sprites/wizard.json"
    },

    sprites: {
        "achievements": { 1: "img/1/achievements.png", 2: "img/2/achievements.png", 3: "img/3/achievements.png" },
        "agent": { 1: "img/1/agent.png", 2: "img/2/agent.png", 3: "img/3/agent.png" },
        "axe": { 1: "img/1/axe.png", 2: "img/2/axe.png", 3: "img/3/axe.png" },
        "barsheet": { 1: "img/1/barsheet.png", 2: "img/2/barsheet.png", 3: "img/3/barsheet.png" },
        "bat": { 1: "img/1/bat.png", 2: "img/2/bat.png", 3: "img/3/bat.png" },
        "beachnpc": { 1: "img/1/beachnpc.png", 2: "img/2/beachnpc.png", 3: "img/3/beachnpc.png" },
        "bluesword": { 1: "img/1/bluesword.png", 2: "img/2/bluesword.png", 3: "img/3/bluesword.png" },
        "border": { 1: "img/1/border.png", 2: "img/2/border.png", 3: "img/3/border.png" },
        "boss": { 1: "img/1/boss.png", 2: "img/2/boss.png", 3: "img/3/boss.png" },
        "chest": { 1: "img/1/chest.png", 2: "img/2/chest.png", 3: "img/3/chest.png" },
        "clotharmor": { 1: "img/1/clotharmor.png", 2: "img/2/clotharmor.png", 3: "img/3/clotharmor.png" },
        "coder": { 1: "img/1/coder.png", 2: "img/2/coder.png", 3: "img/3/coder.png" },
        "crab": { 1: "img/1/crab.png", 2: "img/2/crab.png", 3: "img/3/crab.png" },
        "death": { 1: "img/1/death.png", 2: "img/2/death.png", 3: "img/3/death.png" },
        "deathknight": { 1: "img/1/deathknight.png", 2: "img/2/deathknight.png", 3: "img/3/deathknight.png" },
        "desertnpc": { 1: "img/1/desertnpc.png", 2: "img/2/desertnpc.png", 3: "img/3/desertnpc.png" },
        "eye": { 1: "img/1/eye.png", 2: "img/2/eye.png", 3: "img/3/eye.png" },
        "firefox": { 1: "img/1/firefox.png", 2: "img/2/firefox.png", 3: "img/3/firefox.png" },
        "forestnpc": { 1: "img/1/forestnpc.png", 2: "img/2/forestnpc.png", 3: "img/3/forestnpc.png" },
        "goblin": { 1: "img/1/goblin.png", 2: "img/2/goblin.png", 3: "img/3/goblin.png" },
        "goldenarmor": { 1: "img/1/goldenarmor.png", 2: "img/2/goldenarmor.png", 3: "img/3/goldenarmor.png" },
        "goldensword": { 1: "img/1/goldensword.png", 2: "img/2/goldensword.png", 3: "img/3/goldensword.png" },
        "guard": { 1: "img/1/guard.png", 2: "img/2/guard.png", 3: "img/3/guard.png" },
        "hand": { 1: "img/1/hand.png", 2: "img/2/hand.png", 3: "img/3/hand.png" },
        "item-axe": { 1: "img/1/item-axe.png", 2: "img/2/item-axe.png", 3: "img/3/item-axe.png" },
        "item-bluesword": { 1: "img/1/item-bluesword.png", 2: "img/2/item-bluesword.png", 3: "img/3/item-bluesword.png" },
        "item-burger": { 1: "img/1/item-burger.png", 2: "img/2/item-burger.png", 3: "img/3/item-burger.png" },
        "item-cake": { 1: "img/1/item-cake.png", 2: "img/2/item-cake.png", 3: "img/3/item-cake.png" },
        "item-clotharmor": { 1: "img/1/item-clotharmor.png", 2: "img/2/item-clotharmor.png", 3: "img/3/item-clotharmor.png" },
        "item-firepotion": { 1: "img/1/item-firepotion.png", 2: "img/2/item-firepotion.png", 3: "img/3/item-firepotion.png" },
        "item-flask": { 1: "img/1/item-flask.png", 2: "img/2/item-flask.png", 3: "img/3/item-flask.png" },
        "item-goldenarmor": { 1: "img/1/item-goldenarmor.png", 2: "img/2/item-goldenarmor.png", 3: "img/3/item-goldenarmor.png" },
        "item-goldensword": { 1: "img/1/item-goldensword.png", 2: "img/2/item-goldensword.png", 3: "img/3/item-goldensword.png" },
        "item-leatherarmor": { 1: "img/1/item-leatherarmor.png", 2: "img/2/item-leatherarmor.png", 3: "img/3/item-leatherarmor.png" },
        "item-mailarmor": { 1: "img/1/item-mailarmor.png", 2: "img/2/item-mailarmor.png", 3: "img/3/item-mailarmor.png" },
        "item-morningstar": { 1: "img/1/item-morningstar.png", 2: "img/2/item-morningstar.png", 3: "img/3/item-morningstar.png" },
        "item-platearmor": { 1: "img/1/item-platearmor.png", 2: "img/2/item-platearmor.png", 3: "img/3/item-platearmor.png" },
        "item-redarmor": { 1: "img/1/item-redarmor.png", 2: "img/2/item-redarmor.png", 3: "img/3/item-redarmor.png" },
        "item-redsword": { 1: "img/1/item-redsword.png", 2: "img/2/item-redsword.png", 3: "img/3/item-redsword.png" },
        "item-sword1": { 1: "img/1/item-sword1.png", 2: "img/2/item-sword1.png", 3: "img/3/item-sword1.png" },
        "item-sword2": { 1: "img/1/item-sword2.png", 2: "img/2/item-sword2.png", 3: "img/3/item-sword2.png" },
        "king": { 1: "img/1/king.png", 2: "img/2/king.png", 3: "img/3/king.png" },
        "lavanpc": { 1: "img/1/lavanpc.png", 2: "img/2/lavanpc.png", 3: "img/3/lavanpc.png" },
        "leatherarmor": { 1: "img/1/leatherarmor.png", 2: "img/2/leatherarmor.png", 3: "img/3/leatherarmor.png" },
        "loot": { 1: "img/1/loot.png", 2: "img/2/loot.png", 3: "img/3/loot.png" },
        "mailarmor": { 1: "img/1/mailarmor.png", 2: "img/2/mailarmor.png", 3: "img/3/mailarmor.png" },
        "morningstar": { 1: "img/1/morningstar.png", 2: "img/2/morningstar.png", 3: "img/3/morningstar.png" },
        "nyan": { 1: "img/1/nyan.png", 2: "img/2/nyan.png", 3: "img/3/nyan.png" },
        "octocat": { 1: "img/1/octocat.png", 2: "img/2/octocat.png", 3: "img/3/octocat.png" },
        "ogre": { 1: "img/1/ogre.png", 2: "img/2/ogre.png", 3: "img/3/ogre.png" },
        "platearmor": { 1: "img/1/platearmor.png", 2: "img/2/platearmor.png", 3: "img/3/platearmor.png" },
        "priest": { 1: "img/1/priest.png", 2: "img/2/priest.png", 3: "img/3/priest.png" },
        "rat": { 1: "img/1/rat.png", 2: "img/2/rat.png", 3: "img/3/rat.png" },
        "redarmor": { 1: "img/1/redarmor.png", 2: "img/2/redarmor.png", 3: "img/3/redarmor.png" },
        "redsword": { 1: "img/1/redsword.png", 2: "img/2/redsword.png", 3: "img/3/redsword.png" },
        "rick": { 1: "img/1/rick.png", 2: "img/2/rick.png", 3: "img/3/rick.png" },
        "scientist": { 1: "img/1/scientist.png", 2: "img/2/scientist.png", 3: "img/3/scientist.png" },
        "shadow16": { 1: "img/1/shadow16.png", 2: "img/2/shadow16.png", 3: "img/3/shadow16.png" },
        "skeleton": { 1: "img/1/skeleton.png", 2: "img/2/skeleton.png", 3: "img/3/skeleton.png" },
        "skeleton2": { 1: "img/1/skeleton2.png", 2: "img/2/skeleton2.png", 3: "img/3/skeleton2.png" },
        "snake": { 1: "img/1/snake.png", 2: "img/2/snake.png", 3: "img/3/snake.png" },
        "sorcerer": { 1: "img/1/sorcerer.png", 2: "img/2/sorcerer.png", 3: "img/3/sorcerer.png" },
        "sparks": { 1: "img/1/sparks.png", 2: "img/2/sparks.png", 3: "img/3/sparks.png" },
        "spectre": { 1: "img/1/spectre.png", 2: "img/2/spectre.png", 3: "img/3/spectre.png" },
        "spritesheet": { 1: "img/1/spritesheet.png", 2: "img/2/spritesheet.png", 3: "img/3/spritesheet.png" },
        "sword": { 1: "img/1/sword.png", 2: "img/2/sword.png", 3: "img/3/sword.png" },
        "sword1": { 1: "img/1/sword1.png", 2: "img/2/sword1.png", 3: "img/3/sword1.png" },
        "sword2": { 1: "img/1/sword2.png", 2: "img/2/sword2.png", 3: "img/3/sword2.png" },
        "talk": { 1: "img/1/talk.png", 2: "img/2/talk.png", 3: "img/3/talk.png" },
        "target": { 1: "img/1/target.png", 2: "img/2/target.png", 3: "img/3/target.png" },
        "tilesheet": { 1: "img/1/tilesheet.png", 2: "img/2/tilesheet.png", 3: "img/3/tilesheet.png" },
        "villagegirl": { 1: "img/1/villagegirl.png", 2: "img/2/villagegirl.png", 3: "img/3/villagegirl.png" },
        "villager": { 1: "img/1/villager.png", 2: "img/2/villager.png", 3: "img/3/villager.png" },
        "wizard": { 1: "img/1/wizard.png", 2: "img/2/wizard.png", 3: "img/3/wizard.png" },
        "wood": { 1: "img/1/wood.png", 2: "img/2/wood.png", 3: "img/3/wood.png" },
        "wood2": { 1: "img/1/wood2.png", 2: "img/2/wood2.png", 3: "img/3/wood2.png" },
        "wood3": { 1: "img/1/wood3.png", 2: "img/2/wood3.png", 3: "img/3/wood3.png" }
    },

    // The 67 sprites that game.js instantiates as Sprite image objects.
    // This is a subset of spriteData — it excludes arrow and impact (which have
    // JSON metadata but no corresponding image files) plus item-clotharmor and
    // item-sword1 (which have images but are not used by the game at runtime).
    gameSprites: [
        "hand", "sword", "loot", "target", "talk", "sparks", "shadow16",
        "rat", "skeleton", "skeleton2", "spectre", "boss", "deathknight",
        "ogre", "crab", "snake", "eye", "bat", "goblin", "wizard", "guard",
        "king", "villagegirl", "villager", "coder", "agent", "rick", "scientist",
        "nyan", "priest", "sorcerer", "octocat", "beachnpc", "forestnpc",
        "desertnpc", "lavanpc", "clotharmor", "leatherarmor", "mailarmor",
        "platearmor", "redarmor", "goldenarmor", "firefox", "death", "sword1",
        "axe", "chest", "sword2", "redsword", "bluesword", "goldensword",
        "item-sword2", "item-axe", "item-redsword", "item-bluesword",
        "item-goldensword", "item-leatherarmor", "item-mailarmor",
        "item-platearmor", "item-redarmor", "item-goldenarmor", "item-flask",
        "item-cake", "item-burger", "morningstar", "item-morningstar",
        "item-firepotion"
    ],

    audio: {
        music: {
            "beach": "audio/music/beach.mp3",
            "boss": "audio/music/boss.mp3",
            "cave": "audio/music/cave.mp3",
            "desert": "audio/music/desert.mp3",
            "forest": "audio/music/forest.mp3",
            "lavaland": "audio/music/lavaland.mp3",
            "village": "audio/music/village.mp3"
        },
        sounds: {
            "achievement": "audio/sounds/achievement.mp3",
            "chat": "audio/sounds/chat.mp3",
            "chest": "audio/sounds/chest.mp3",
            "death": "audio/sounds/death.mp3",
            "firefox": "audio/sounds/firefox.mp3",
            "heal": "audio/sounds/heal.mp3",
            "hit1": "audio/sounds/hit1.mp3",
            "hit2": "audio/sounds/hit2.mp3",
            "hurt": "audio/sounds/hurt.mp3",
            "kill1": "audio/sounds/kill1.mp3",
            "kill2": "audio/sounds/kill2.mp3",
            "loot": "audio/sounds/loot.mp3",
            "noloot": "audio/sounds/noloot.mp3",
            "npc": "audio/sounds/npc.mp3",
            "npc-end": "audio/sounds/npc-end.mp3",
            "npctalk": "audio/sounds/npctalk.mp3",
            "revive": "audio/sounds/revive.mp3",
            "teleport": "audio/sounds/teleport.mp3"
        }
    },

    tilesets: {
        1: "img/1/tilesheet.png",
        2: "img/2/tilesheet.png",
        3: "img/3/tilesheet.png"
    },

    maps: {
        world: "maps/world_client.json",
        worldWorker: "maps/world_client.js",
        worldServer: "maps/world_server.json"
    }
};

export default manifest;
